"""
Build script for the Strategic Partners Playbook 3.0 hub.
Reads structured content from content/ and produces dist/index.html.
Never hand-edit dist/index.html - it is regenerated by this script and
overwritten on every build. Edit files in content/ instead, following
meta/update-protocol.md.
"""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
CONTENT = os.path.join(ROOT, "content")
DIST = os.path.join(ROOT, "dist")

with open(os.path.join(CONTENT, "manifest.json")) as f:
    manifest = json.load(f)
with open(os.path.join(CONTENT, "queued.json")) as f:
    queued = json.load(f)
with open(os.path.join(CONTENT, "categories.json")) as f:
    cats = json.load(f)
with open(os.path.join(CONTENT, "changelog.json")) as f:
    changelog = json.load(f)

docs = []
for entry in manifest:
    with open(os.path.join(CONTENT, entry["content_file"])) as f:
        body = f.read()
    d = dict(entry)
    d["html"] = body
    docs.append(d)

CSS = """
:root{
  --ink:#211f1c; --ink-soft:#5c5850; --ink-faint:#948e83;
  --paper:#FAF8F4; --panel:#FFFFFF; --line:#E4DFD6; --line-strong:#CFC8BA;
  --sidebar:#20241F; --sidebar-line:#343930; --sidebar-text:#C9CDBE; --sidebar-text-dim:#7C8072;
  --accent:#5B6E4F; --accent-soft:#E7ECDF;
  --green:#3F7D4A; --green-bg:#E5F0E2;
  --amber:#A6740F; --amber-bg:#FAF0DB;
  --red:#B14A3E; --red-bg:#F8E5E1;
  --radius:10px;
}
*{box-sizing:border-box;}
body{margin:0;font-family:'Inter',sans-serif;background:var(--paper);color:var(--ink);}
.sidebar{position:fixed;top:0;left:0;height:100vh;width:290px;background:var(--sidebar);z-index:50;overflow-y:auto;padding-bottom:1rem;transform:translateX(calc(-100% + 14px));transition:transform .22s ease;box-shadow:6px 0 28px rgba(0,0,0,.28);}
.sidebar:hover,.sidebar.pinned{transform:translateX(0);}
.sidebar-edge{position:absolute;top:0;right:0;width:14px;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;background:linear-gradient(180deg,#2A2F26,#20241F);border-left:1px solid #343930;}
.sidebar-edge .dot-hint{width:3px;height:3px;border-radius:50%;background:#6B7060;}
.pin-btn{position:absolute;top:14px;right:22px;width:22px;height:22px;border-radius:6px;background:#2A2F26;color:var(--sidebar-text-dim);display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:11px;border:1px solid #3E4438;}
.pin-btn:hover{color:#F2F0E7;}
.pin-btn.active{background:#8CA478;color:#1B1F17;border-color:#8CA478;}
.sidebar-header{padding:1.5rem 2rem 1rem 1.25rem;border-bottom:1px solid var(--sidebar-line);}
.brand{font-family:'Fraunces',serif;font-size:16px;font-weight:600;color:#F2F0E7;cursor:pointer;line-height:1.3;}
.progress-mini{font-family:'JetBrains Mono',monospace;font-size:10.5px;color:var(--sidebar-text-dim);margin-top:4px;}
.progress-track{height:3px;background:#343930;border-radius:3px;overflow:hidden;margin-top:8px;}
.progress-fill{height:100%;background:#8CA478;border-radius:3px;}
.cat-block{border-bottom:1px solid #2A2E26;}
.cat-header{display:flex;align-items:center;gap:9px;padding:11px 1.25rem;cursor:pointer;font-size:13px;font-weight:500;color:#E4E7D8;user-select:none;}
.cat-header:hover{background:#262B22;}
.cat-header.active-cat{background:#262B22;}
.chevron{font-size:9px;color:var(--sidebar-text-dim);transition:transform .15s ease;width:10px;flex-shrink:0;}
.chevron.open{transform:rotate(90deg);}
.tab-num{font-family:'JetBrains Mono',monospace;font-size:10px;background:#343930;color:#A8AC9B;width:16px;height:16px;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;}
.cat-header.active-cat .tab-num{background:#8CA478;color:#1B1F17;}
.cat-count{margin-left:auto;font-family:'JetBrains Mono',monospace;font-size:10px;color:var(--sidebar-text-dim);}
.cat-body{overflow:hidden;max-height:0;transition:max-height .18s ease;}
.cat-body.open{max-height:600px;}
.doc-link{display:flex;align-items:center;gap:8px;padding:8px 1.25rem 8px 2.5rem;font-size:12.5px;color:var(--sidebar-text-dim);cursor:pointer;}
.doc-link:hover{background:#262B22;color:var(--sidebar-text);}
.doc-link.active{background:#262B22;color:#F2F0E7;border-left:2px solid #8CA478;padding-left:calc(2.5rem - 2px);}
.doc-link.disabled{cursor:default;opacity:.55;}
.tab-num-sm{font-family:'JetBrains Mono',monospace;font-size:9.5px;color:var(--sidebar-text-dim);flex-shrink:0;}
.dot{width:6px;height:6px;border-radius:50%;flex-shrink:0;}
.dot-done{background:#7BBE86;}
.dot-draft{background:#E0B04A;}
.dot-pending{background:#6B6F60;}
.changelog-link{display:flex;align-items:center;gap:8px;padding:11px 1.25rem;font-size:12.5px;color:var(--sidebar-text-dim);cursor:pointer;border-top:1px solid var(--sidebar-line);margin-top:6px;}
.changelog-link:hover{color:#F2F0E7;}
.main{margin-left:30px;max-width:840px;padding:3rem 2rem 5rem;}
.crumb{font-family:'JetBrains Mono',monospace;font-size:11px;color:var(--ink-faint);text-transform:uppercase;letter-spacing:.04em;margin-bottom:10px;}
.doc-header{border-bottom:1px solid var(--line);padding-bottom:1.25rem;margin-bottom:1.75rem;}
.doc-title{font-family:'Fraunces',serif;font-size:30px;font-weight:600;margin:0 0 8px;line-height:1.15;}
.meta-row{display:flex;gap:14px;align-items:center;flex-wrap:wrap;}
.badge{font-family:'JetBrains Mono',monospace;font-size:11px;padding:3px 9px;border-radius:20px;font-weight:500;white-space:nowrap;}
.badge-done{background:var(--green-bg);color:var(--green);}
.badge-draft{background:var(--amber-bg);color:var(--amber);}
.badge-pending{background:var(--red-bg);color:var(--red);}
.meta-text{font-size:12px;color:var(--ink-faint);font-family:'JetBrains Mono',monospace;}
.content{font-size:15px;line-height:1.75;color:var(--ink);}
.content h2{font-family:'Fraunces',serif;font-size:19px;font-weight:600;margin:2rem 0 .75rem;padding-top:.5rem;}
.content h2:first-child{margin-top:0;}
.content p{margin:0 0 1rem;color:var(--ink-soft);}
.content ul,.content ol{margin:0 0 1rem;padding-left:1.3rem;color:var(--ink-soft);}
.content li{margin-bottom:5px;}
.content strong{font-weight:600;color:var(--ink);}
a.xlink{color:var(--accent);text-decoration:underline;text-decoration-color:var(--line-strong);text-underline-offset:2px;cursor:pointer;font-weight:500;}
a.xlink:hover{text-decoration-color:var(--accent);}
table.dtable{width:100%;border-collapse:collapse;margin:0 0 1.5rem;font-size:13px;}
table.dtable th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.03em;color:var(--ink-faint);border-bottom:1px solid var(--line-strong);padding:7px 10px 7px 0;font-weight:500;}
table.dtable td{padding:9px 10px 9px 0;border-bottom:1px solid var(--line);vertical-align:top;color:var(--ink-soft);}
table.dtable td:first-child,table.dtable th:first-child{color:var(--ink);font-weight:500;}
.callout{background:var(--accent-soft);border-left:3px solid var(--accent);border-radius:0 8px 8px 0;padding:12px 16px;margin:0 0 1.25rem;font-size:13.5px;color:#3F4D36;}
.pending-box{background:var(--panel);border:1px dashed var(--line-strong);border-radius:var(--radius);padding:1.5rem;text-align:center;color:var(--ink-faint);font-size:13.5px;}
.status-pill{display:inline-flex;align-items:center;gap:6px;font-family:'JetBrains Mono',monospace;font-size:10.5px;padding:2px 8px;border-radius:20px;margin-left:6px;vertical-align:middle;}
.cl-item{display:flex;gap:16px;padding:14px 0;border-bottom:1px solid var(--line);}
.cl-date{font-family:'JetBrains Mono',monospace;font-size:11px;color:var(--ink-faint);width:100px;flex-shrink:0;padding-top:2px;}
.cl-body strong{display:block;margin-bottom:2px;}
.cl-body span{font-size:13px;color:var(--ink-soft);}
[data-tip]{position:relative;}
[data-tip]:hover::after{content:attr(data-tip);position:absolute;top:50%;left:100%;transform:translateY(-50%);margin-left:10px;z-index:20;background:#12140F;color:#E9E7DD;font-family:'Inter',sans-serif;font-size:12px;font-weight:400;line-height:1.45;padding:8px 11px;border-radius:8px;width:max-content;max-width:220px;white-space:normal;box-shadow:0 4px 14px rgba(0,0,0,.28);pointer-events:none;}
[data-tip]:hover::before{content:"";position:absolute;top:50%;left:100%;transform:translateY(-50%);margin-left:2px;border:5px solid transparent;border-right-color:#12140F;z-index:20;pointer-events:none;}
@media(max-width:900px){.sidebar{position:static;height:auto;width:100%;transform:none;box-shadow:none;}.sidebar-edge,.pin-btn{display:none;}.main{margin-left:0;padding:2rem 1.25rem 4rem;max-width:none;}[data-tip]:hover::after,[data-tip]:hover::before{display:none;}}
"""

docs_js = json.dumps(docs)
queued_js = json.dumps(queued)
changelog_js = json.dumps(changelog)
cats_js = json.dumps(cats["order"])
cat_desc_js = json.dumps(cats["descriptions"])

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Strategic Partners Playbook 3.0 - Project Hub</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>{CSS}</style>
</head>
<body>
<nav class="sidebar" id="sidebar">
  <div class="sidebar-edge"><span class="dot-hint"></span><span class="dot-hint"></span><span class="dot-hint"></span></div>
  <div class="pin-btn" id="pinBtn" onclick="togglePin()" title="Keep menu open">&#128204;</div>
  <div id="sidebarContent"></div>
</nav>
<main class="main" id="main"></main>

<script>
const DOCS = {docs_js};
const QUEUED = {queued_js};
const CHANGELOG = {changelog_js};
const CATS_ORDER = {cats_js};
const CAT_DESC = {cat_desc_js};

let activeCat = "Strategic Planning";
let expandedCats = new Set(["Strategic Planning"]);

function statusBadge(status){{
  if(status==="done") return '<span class="badge badge-done">Confirmed</span>';
  if(status==="draft") return '<span class="badge badge-draft">Draft</span>';
  return '<span class="badge badge-pending">Pending</span>';
}}
function dotClass(status){{
  if(status==="done") return "dot-done";
  if(status==="draft") return "dot-draft";
  return "dot-pending";
}}

function buildSidebar(activeId){{
  const done = DOCS.length, total = DOCS.length + QUEUED.length;
  const pct = Math.round((done/total)*100);

  let html = `<div class="sidebar-header">
    <div class="brand" onclick="showDoc('guide')">Strategic Partners Playbook 3.0</div>
    <div class="progress-mini">${{done}} of ${{total}} drafted (${{pct}}%)</div>
    <div class="progress-track"><div class="progress-fill" style="width:${{pct}}%"></div></div>
  </div>`;

  let catNum = 0;
  CATS_ORDER.forEach(cat => {{
    const docsInCat = DOCS.filter(d=>d.cat===cat);
    const queuedInCat = QUEUED.filter(q=>q.cat===cat);
    const total_in_cat = docsInCat.length + queuedInCat.length;
    if(total_in_cat===0) return;
    catNum++;
    const isOpen = expandedCats.has(cat);
    const isActiveCat = cat===activeCat;
    const tip = (CAT_DESC[cat] || '').replace(/"/g, '&quot;');

    html += `<div class="cat-block">
      <div class="cat-header ${{isActiveCat?'active-cat':''}}" data-tip="${{tip}}" onclick="toggleCat('${{cat}}')">
        <span class="chevron ${{isOpen?'open':''}}">&#9656;</span>
        <span class="tab-num">${{catNum}}</span>
        <span>${{cat}}</span>
        <span class="cat-count">${{docsInCat.length}}/${{total_in_cat}}</span>
      </div>
      <div class="cat-body ${{isOpen?'open':''}}">`;

    let docNum = 0;
    docsInCat.forEach(d=>{{
      docNum++;
      const cls = d.id===activeId ? 'doc-link active' : 'doc-link';
      const dtip = (d.desc || '').replace(/"/g, '&quot;');
      html += `<div class="${{cls}}" data-tip="${{dtip}}" onclick="showDoc('${{d.id}}')"><span class="tab-num-sm">${{docNum}}</span><span class="dot ${{dotClass(d.status)}}"></span>${{d.title}}</div>`;
    }});
    queuedInCat.forEach(q=>{{
      docNum++;
      const dtip = (q.desc || '').replace(/"/g, '&quot;');
      html += `<div class="doc-link disabled" data-tip="${{dtip}}"><span class="tab-num-sm">${{docNum}}</span><span class="dot dot-pending"></span>${{q.title}}</div>`;
    }});

    html += `</div></div>`;
  }});

  html += `<div class="changelog-link" onclick="showChangelog()">Version history</div>`;
  document.getElementById('sidebarContent').innerHTML = html;
}}

function togglePin(){{
  const sb = document.getElementById('sidebar');
  const btn = document.getElementById('pinBtn');
  sb.classList.toggle('pinned');
  btn.classList.toggle('active');
}}

function toggleCat(cat){{
  if(expandedCats.has(cat)) expandedCats.delete(cat);
  else expandedCats.add(cat);
  activeCat = cat;
  buildSidebar(currentDocId);
}}

let currentDocId = null;

function renderEmpty(cat){{
  document.getElementById('main').innerHTML = `<div class="crumb">${{cat}}</div><div class="doc-header"><h1 class="doc-title">Not yet drafted</h1></div><div class="pending-box">Everything in this category is still queued. Check Master Execution Sequence for build order.</div>`;
}}

function showDoc(id){{
  const d = DOCS.find(x=>x.id===id);
  if(!d) return;
  activeCat = d.cat;
  currentDocId = id;
  expandedCats.add(d.cat);
  buildSidebar(id);
  document.getElementById('main').innerHTML = `
    <div class="crumb">${{d.cat}}</div>
    <div class="doc-header">
      <h1 class="doc-title">${{d.title}}</h1>
      <div class="meta-row">${{statusBadge(d.status)}}<span class="meta-text">v${{d.version}}</span><span class="meta-text">.</span><span class="meta-text">${{d.type}}</span><span class="meta-text">.</span><span class="meta-text">${{d.updated}}</span></div>
    </div>
    <div class="content">${{d.html}}</div>
  `;
  window.scrollTo(0,0);
}}

function showChangelog(){{
  currentDocId = null;
  buildSidebar(null);
  let items = CHANGELOG.map(c=>`<div class="cl-item"><div class="cl-date">${{c.date}}</div><div class="cl-body"><strong>${{c.title}}</strong><span>${{c.desc}}</span></div></div>`).join("");
  document.getElementById('main').innerHTML = `<div class="crumb">Project hub</div><div class="doc-header"><h1 class="doc-title">Version history</h1><div class="meta-row"><span class="meta-text">Every structural change to this hub, logged here</span></div></div><div class="content">${{items}}</div>`;
  window.scrollTo(0,0);
}}

showDoc('guide');
</script>
</body>
</html>"""


os.makedirs(DIST, exist_ok=True)
with open(os.path.join(DIST, "index.html"), "w") as f:
    f.write(html)

domain_file = os.path.join(ROOT, "meta", "custom-domain.txt")
if os.path.exists(domain_file):
    with open(domain_file) as f:
        domain = f.read().strip()
    if domain:
        with open(os.path.join(DIST, "CNAME"), "w") as f:
            f.write(domain + "\n")
        print("Custom domain set:", domain)

print("Built dist/index.html -", len(html), "chars,", len(docs), "documents,", len(queued), "queued")
